


steps:
- name: 'node'
  entrypoint: 'npm'
  args: ['install']


- name: 'node'
  entrypoint: 'npm'
  args: ['run', 'build']


- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gsutil', 'cp', '-r', 'build/*', 'gs://demo1frontendtleboucq/']
